block.search_results.prerender:
    listeners:
        - [BackBuilder\Bundle\GSABundle\Listener\SearchResultsListener, onPrerenderSearch]
block.search_textbox.prerender:
    listeners:
        - [BackBuilder\Bundle\GSABundle\Listener\SearchTextboxListener, onPrerenderSearch]