block.searchresults.prerender:
    listeners:
        - [BackBee\Bundle\GSABundle\Listener\SearchResultsListener, onPrerenderSearch]
block.searchtextbox.prerender:
    listeners:
        - [BackBee\Bundle\GSABundle\Listener\SearchTextboxListener, onPrerenderSearch]