gsa.bundle.search:
    pattern: /search
    defaults:
        _action: searchAction
    requirements:
        _method: GET

gsa.bundle.suggest:
    pattern: /suggest
    defaults: { _action: suggestAction }
    requirements:
        _method: GET

gsa.bundle.typology:
    pattern: /typology
    defaults: { _action: typologyAction }
    requirements:
        _method: GET

gsa.bundle.cluster:
    pattern: /cluster
    defaults: { _action: clusterAction }
    requirements:
        _method: POST
