bundle:
    name: GSA
    description: 'Utils to query a google search appliance engine'
    author: 'Next Interactive Media'
    version: 1
    enable: on
    thumbnail: "img/extnd-x/picto-extnd-gsa.png"
    #service: BackBuilder\Bundle\PollBundle\Services\Local\Poll
    #manage_multisite: false

route:
    gsa.bundle.search:
        pattern: /search
        defaults: 
            _action: searchAction
        requirements:
            _method: GET

    gsa.bundle.suggest:
        pattern: /suggest
        defaults: { _action: suggestAction }
        requirements:
            _method: GET

    gsa.bundle.typology:
        pattern: /typology
        defaults: { _action: typologyAction }
        requirements:
            _method: GET

    gsa.bundle.cluster:
        pattern: /cluster
        defaults: { _action: clusterAction }
        requirements:
            _method: POST

events:
    block.search_results.prerender: { listeners: [[BackBuilder\Bundle\GSABundle\Listener\SearchResultsListener, onPrerenderSearch]] }
    block.search_textbox.prerender: { listeners: [[BackBuilder\Bundle\GSABundle\Listener\SearchTextboxListener, onPrerenderSearch]] }